# Dockerfile
FROM envoyproxy/envoy-alpine:v1.17.0

COPY ./envoy/envoy.yaml /etc/envoy/envoy.yaml
COPY ./target/generated-resources/protobuf/descriptor-sets/grpc-rest-${project.version}.protobin /etc/envoy/proto.pd

CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
